<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tri-snake">
  <xacro:property name="baselen" value="10"/>
  <xacro:property name="baseheight" value="4"/>
  <xacro:property name="bodylen" value="7.6"/>
  <xacro:property name="joint_offset" value="0.5"/>
    
  <material name="blue">
    <color rgba="0 0 0.8 0.7"/>
  </material>
    
  <material name="green">
    <color rgba="0 0.8 0 0.7"/>
  </material>
    
  <link name="base">
    <visual>
      <geometry>
        <box size="10 5 4"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>

  <!-- First chain -->
  <joint name="body1_to_base" type="revolute">
    <parent link="base"/>
    <child link="body1"/>
    <origin rpy="0 0 0" xyz="${baselen-joint_offset} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>
  	
  <link name="body1">
    <visual>
      <geometry>
        <box size="7.6 4.7 2.6"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${bodylen-joint_offset} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="body2_to_body1" type="revolute">
    <parent link="body1"/>
    <child link="body2"/>
    <origin rpy="0 0 0" xyz="${bodylen*2-joint_offset*2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>
    
  <link name="body2">
    <visual>
      <geometry>
        <box size="7.6 2.4 5.3"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${bodylen-joint_offset} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="body3_to_body2" type="revolute">
    <parent link="body2"/>
    <child link="body3"/>
    <origin rpy="0 0 0" xyz="${bodylen*2-joint_offset*2} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>

  <link name="body3">
    <visual>
      <geometry>
        <box size="7.6 6.4 2.16"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${bodylen-joint_offset} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <!-- Second chain -->
  <joint name="body4_to_base" type="revolute">
    <parent link="base"/>
    <child link="body4"/>
    <origin rpy="0 0 0" xyz="${-(baselen-joint_offset)} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>
  	
  <link name="body4">
    <visual>
      <geometry>
        <box size="7.6 3.27 1.4"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${-(bodylen-joint_offset)} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="body5_to_body4" type="revolute">
    <parent link="body4"/>
    <child link="body5"/>
    <origin rpy="0 0 0" xyz="${-(bodylen*2-joint_offset*2)} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>
    
  <link name="body5">
    <visual>
      <geometry>
        <box size="7.6 2.7 4.4"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${-(bodylen-joint_offset)} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="body6_to_body5" type="revolute">
    <parent link="body5"/>
    <child link="body6"/>
    <origin rpy="0 0 0" xyz="${-(bodylen*2-joint_offset*2)} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>

  <link name="body6">
    <visual>
      <geometry>
        <box size="7.6 4.7 2.4"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${-(bodylen-joint_offset)} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>

  <!-- Third chain -->
  <joint name="body7_to_base" type="revolute">
    <parent link="base"/>
    <child link="body7"/>
    <origin rpy="0 0 0" xyz="0 0 ${baseheight-joint_offset}"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>
  	
  <link name="body7">
    <visual>
      <geometry>
        <box size="3.5 4.7 7.6"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${bodylen-joint_offset} "/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="body8_to_body7" type="revolute">
    <parent link="body7"/>
    <child link="body8"/>
    <origin rpy="0 0 0" xyz="0 0 ${bodylen*2-joint_offset*2}"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>
    
  <link name="body8">
    <visual>
      <geometry>
        <box size="1.2 4.7 7.6"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${bodylen-joint_offset}"/>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="body9_to_body8" type="revolute">
    <parent link="body8"/>
    <child link="body9"/>
    <origin rpy="0 0 0" xyz="0 0 ${bodylen*2-joint_offset*2}"/>
    <axis xyz="1 0 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="5"/>
  </joint>

  <link name="body9">
    <visual>
      <geometry>
        <box size="6.5 4.7 7.6"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${bodylen-joint_offset}"/>
      <material name="blue"/>
    </visual>
  </link>
    
</robot>
