name: C++ CI Sanitizers Address and Memory
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Build-and-Test-Sanitizers-Address-Memory:
    runs-on: ubuntu-20.04
    container:
        image: robotma/highwayroadmap-gcc-9:latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Environement
        run: pwd && echo $USER
      - name: Sanitize Address
        run: |
          cd .. && mkdir tmpBuild && cd tmpBuild
          cmake -G Ninja -DSANITIZE_ADDRESS=ON ../hrm && ninja -j 9
      - name: Sanitize Memory
        run: |
          cmake -G Ninja -DSANITIZE_MEMORY=ON ../hrm && ninja -j 9
